# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Call for Papers
    url: /call-for-papers
    weight: 20
  - name: Invited Speakers
    url: /invited-speakers
    weight: 30
  - name: Program
    url: /program
    weight: 40
  - name: Committees
    url: /committees
    weight: 50
  - name: Registration
    url: /registration
    weight: 60
  - name: Venue
    url: /venue
    weight: 70
